//品牌控制层		
app.controller('brandController',function($scope,$controller,brandService){
	
	//指定要继承那个controller
	$controller('baseController',{$scope:$scope});
	
	$scope.findAll=function(){
		brandService.findAll().success(
			function(response){
				$scope.list=response;
			}	
		);
	};
	//分页方法
	$scope.findPage=function(page,size){
		brandService.findPage(page,size).success(
			function(response){
				$scope.list=response.rows;//显示当前页的数据
				$scope.paginationConf.totalItems=response.total;//更新总记录	
			}
		);
	};
	
	//新增品牌列表
	$scope.save=function(){
		if($scope.entity.id!=null){
			object=brandService.update($scope.entity);
		}else{
			object=brandService.add($scope.entity);
		}
		object.success(
			function(response){
				if(response.success){//如果成功
					$scope.reloadList();//刷新列表
				}else{
					alert(response.message);//提示错误
				}	
			}
		);
	};
	//根据id查找品牌记录
	$scope.findOne=function(id){
		//$http.get('../brand/findOne.do?id='+id)
		brandService.findOne(id).success(
			function(response){
				$scope.entity=response;
			}		
		);
	}
	
	
	//根据ID删除记录
	$scope.dele=function(){
		//$http.get("../brand/delete.do?ids="+$scope.selectIds)
		brandService.dele($scope.selectIds).success(
			function(response){
				if(response.success){
					$scope.reloadList();
				}else{
					alert(response.message);
				}
			}	
		)
	}
	$scope.searchEntity={};
	//条件查询
	$scope.search=function(page,size){
		//$http.post("../brand/search.do?page="+page+"&size="+size,$scope.searchEntity)
		brandService.search(page,size,$scope.searchEntity).success(
			function(response){
				$scope.list=response.rows;//显示当前页的数据
				$scope.paginationConf.totalItems=response.total;//更新总记录	
			}	
		)
	}
	
});